server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/payment_db?createDatabaseIfNotExist=true
    username: root
    password: Abcd@1234
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:9296
